version: '3.7'

services:
  messenger:
    container_name: messenger
    image: pavellpp/messenger:v16

    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database
    depends_on:
      - database
    networks:
      - backend

  database:
    container_name: database
    ports:
      - "5432:5432"
    image: postgres
    environment:
      - POSTGRES_PASSWORD=4864
    networks:
      - backend

networks:
  backend:
    driver: bridge